# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slamy < Formula
  desc "A CLI tool and MCP server for Slack operations"
  homepage "https://github.com/tackeyy/slamy"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tackeyy/slamy/releases/download/v0.1.0/slamy_0.1.0_darwin_amd64.tar.gz"
      sha256 "dd7dcf47a4dab8136c4694dc70e01f25e57885f7d3a554bb8983f67865e53a1e"

      def install
        bin.install "slamy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tackeyy/slamy/releases/download/v0.1.0/slamy_0.1.0_darwin_arm64.tar.gz"
      sha256 "8eefccb66bf38b2bc95e5659b3542b39dd5c4bbd2d4069909f5070a59a39449a"

      def install
        bin.install "slamy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tackeyy/slamy/releases/download/v0.1.0/slamy_0.1.0_linux_amd64.tar.gz"
      sha256 "e93a02b0a247818fd9781694e3543952a067da6d647261348c192d8da0ca7d6d"
      def install
        bin.install "slamy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tackeyy/slamy/releases/download/v0.1.0/slamy_0.1.0_linux_arm64.tar.gz"
      sha256 "9ed172ec309c72f587579d7b33910e3e3892b9c550fd0905643ce2b8603a4729"
      def install
        bin.install "slamy"
      end
    end
  end
end
