# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ticky < Formula
  desc "A CLI tool for TickTick task management"
  homepage "https://github.com/tackeyy/ticky"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tackeyy/ticky/releases/download/v0.1.0/ticky_0.1.0_darwin_amd64.tar.gz"
      sha256 "6a287d6a78cfd015412e1fa34ce5f915dd49bf8d5e3e658022ee3db8ec3e4f88"

      def install
        bin.install "ticky"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tackeyy/ticky/releases/download/v0.1.0/ticky_0.1.0_darwin_arm64.tar.gz"
      sha256 "0df83a16ffd783e35969dde55822ea227c971bf365c082c89d5a466878f7a91b"

      def install
        bin.install "ticky"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tackeyy/ticky/releases/download/v0.1.0/ticky_0.1.0_linux_amd64.tar.gz"
      sha256 "5e905ec66d6b978a2fb38a3529411e791a90a9d59b55228438edca7f569ca5dd"
      def install
        bin.install "ticky"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tackeyy/ticky/releases/download/v0.1.0/ticky_0.1.0_linux_arm64.tar.gz"
      sha256 "415a809be5ee980449c5faad10713549dbe74e39b63e2cef3694718c116942f0"
      def install
        bin.install "ticky"
      end
    end
  end
end
