# This file was generated by GoReleaser. DO NOT EDIT.
cask "slamy" do
  name "slamy"
  desc "A CLI tool and MCP server for Slack operations"
  homepage "https://github.com/tackeyy/slamy"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slamy"

  on_macos do
    on_intel do
      url "https://github.com/tackeyy/slamy/releases/download/v#{version}/slamy_#{version}_darwin_amd64.tar.gz"
      sha256 "7852388a3b24ee8e9785e70e04042193b5771705bce04363f04af4fc4a69bd39"
    end
    on_arm do
      url "https://github.com/tackeyy/slamy/releases/download/v#{version}/slamy_#{version}_darwin_arm64.tar.gz"
      sha256 "2e9fde58064a359199b4e2c19670bf8a3a3d504dfeafb1148c4e809212403aae"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tackeyy/slamy/releases/download/v#{version}/slamy_#{version}_linux_amd64.tar.gz"
      sha256 "a6f48a7890d5cd2d2b0586c4a6fa0a155c980af2ba9f241dabf923d92ff7530c"
    end
    on_arm do
      url "https://github.com/tackeyy/slamy/releases/download/v#{version}/slamy_#{version}_linux_arm64.tar.gz"
      sha256 "89cf5a0dc39146f2e4fdfa26ef2f19628f7098c3f31cd90db1c435f6cc68df41"
    end
  end

  # No zap stanza required
end
